version: "3.7"
services:
  db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - C:\Users\amber\OneDrive\Documents\volumes:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
